# This file contains the configuration values for the chatbot application deployment
# Global configuration for the chatbot application
global: 
  domain: example.io # Domain for the chatbot application

# General configuration
name: chatbot-backend # Name of the chatbot backend service
replicas: 1 # Number of replicas for the chatbot backend service
domain: example.io # Domain for the chatbot backend service
env:
  vsAgentAdminUrl: http://chatbot:3000 # URL for the VS Agent Admin API
  visionUrl: http://webrtc-pymediasoup-client.example.io # URL for the Vision Service demo
  # visionServiceName: webrtc-pymediasoup-client # Name of the Vision Service, used to construct the URL if not provided visionUrl
  # only recomended if the Vision Service is not running in the same cluster
  webrtcUrl: https://webrtc.example.io # WebRTC server URL, used for video calls and media streaming 
  # webrtcServiceName: webrtc-server # Name of the WebRTC service, used to construct the URL if not provide webrtcUrl
  # only recomended if the webrtc server is not running in the same cluster
  port: 5000 # Port on which the chatbot backend service listens

# VS Agent Chart dependency configuration
# This section defines the configuration for the VS Agent chart that is used by the chatbot application
# It includes the agent name, replicas, domain, and other settings
vs-agent-chart:
  enabled: false # Indicates whether the VS Agent chart is enabled
  name: chatbot # Name of the VS Agent chart
  didcommLabel: Chatbot Agent # Chatbot name to display on the invitation QR code
  eventsBaseUrl: http://chatbot-backend:5000 # Base URL for the chatbot backend service
  didcommInvitationImageUrl: https://image.example.io/avatar.png # Image for the chatbot invitation QR code
  includeAnoncredsEnv: true # Whether to include AnonCreds environment

  # Environment variables specific to the chatbot backend service
  extraEnv: 
    - name: REDIRECT_DEFAULT_URL_TO_INVITATION_URL
      value: "true"
    - name: AGENT_WALLET_ID
      value: "Chatbot Agent"
    - name: AGENT_WALLET_KEY
      value: "Chatbot Agent"
    - name: AGENT_WALLET_KEY_DERIVATION_METHOD
      value: "ARGON2I_MOD"
