@startuml verifier example
actor User as "DIDComm Wallet"
participant "VS Agent" as Agent
participant "Verifier Service" as Verifier

User -> Agent : Scan QR (invitation/qr)
Agent -> User : Send invitation
User -> Agent : Establish connection
Agent -> Verifier : Forward connection event
Verifier -> Agent : Send proof request
Agent -> User : Deliver presentation request
User -> Agent : Present credential
Agent -> Verifier : Forward presentation
Verifier -> Agent : Send verification result
Agent -> User : Deliver result
@enduml