version: '3'

services:
  vs-agent:
    build: ../..
    image: 2060-vs-agent
    container_name: phonenumbervs-vs-agent
    restart: always
    networks:
      - phonenumbervs
    ports:
      - 3100:3000
      - 3101:3001
    environment:
      - AGENT_PUBLIC_DID=did:web:10.82.14.12%3A3101
      - AGENT_ENDPOINT=ws://10.82.14.12:3101
      - ANONCREDS_BASE_URL=http://10.82.14.12:3101
      - AGENT_NAME=Phone Number Verification Service Agent
      - USE_CORS=true
      - EVENTS_BASE_URL=http://phonenumbervs-backend:5000
    volumes:
      - ./afj:/root/.afj

  phonenumbervs-backend:
    build: .
    image: 2060-vs-agent-phonenumbervs
    container_name: phonenumbervs-backend
    restart: always
    networks:
      - phonenumbervs
    ports:
      - 5100:5000
    environment:
      - PORT=5000
      - VS_AGENT_ADMIN_BASE_URL=http://phonenumbervs-vs-agent:3000

  redis:
    image: redis:alpine
    restart: always
    networks:
      - phonenumbervs
    ports:
      - 6379:6379
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:15.2
    restart: always
    networks:
      - phonenumbervs
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=64270demo
      - POSTGRES_USER=emailvs
networks:
  phonenumbervs:
