apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vsAgentName }}
  namespace: {{ .Values.vsAgentNamespace }}
  labels:
    app: {{ .Values.vsAgentName }}
spec:
  selector:
    app: {{ .Values.vsAgentName }}
  ports:
  - name: didcomm
    port: {{ .Values.agentPort }}
    targetPort: {{ .Values.agentPort }}
    protocol: TCP
  - name: admin
    port: {{ .Values.adminPort }}
    targetPort: {{ .Values.adminPort }}
    protocol: TCP
  - name: db
    port: 5432
    targetPort: 5432
    protocol: TCP
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
---
# Public ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-{{ .Values.vsAgentName }}
  namespace: {{ .Values.vsAgentNamespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.ingress.public.enableCors | default "true" }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.vsAgentName }}.{{ .Values.vsAgentDomain }}
      secretName: public.{{ .Values.vsAgentName }}.{{ .Values.vsAgentDomain }}-cert
  rules:
    - host: {{ .Values.vsAgentName }}.{{ .Values.vsAgentDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.vsAgentName }}
                 port:
                   number: {{ .Values.agentPort }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.vsAgentName }}-vsa-pv
  namespace: {{ .Values.vsAgentNamespace }}
  labels:
    app: {{ .Values.vsAgentName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: {{ .Values.storage.storageClassName | default "csi-cinder-high-speed" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
---
{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pg-pv-main
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: csi-cinder-classic
  resources:
    requests:
      storage: 1Gi
{{- end }}
---
{{- if .Values.images.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-redis-main
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: csi-cinder-classic
  resources:
    requests:
      storage: 1Gi
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: {{ .Values.vsAgentName }}
   namespace: {{ .Values.vsAgentNamespace }}
spec:
   serviceName: {{ .Values.vsAgentName }}
   replicas: {{ .Values.vsAgentReplicas }}
   selector:
      matchLabels:
         app: {{ .Values.vsAgentName }}
   template:
      metadata:
         labels:
            app: {{ .Values.vsAgentName }}
      spec:
         containers:
         -  name: {{ .Values.vsAgentName }}-sa-container
            image: "{{ .Values.images.agent.repository }}:{{ .Values.images.agent.tag }}"
            imagePullPolicy: Always
            env:
            - name: AGENT_ENDPOINT
              value: "wss://{{ .Values.vsAgentName }}.{{ .Values.vsAgentDomain }}:443"
            - name: AGENT_LABEL
              value: {{ .Values.agentName }}
            - name: AGENT_INVITATION_IMAGE_URL
              value: "{{ .Values.images.invitationUrl }}"
            - name: EVENTS_BASE_URL
              value: "{{ .Values.eventsBaseUrl }}"
            - name: AGENT_PUBLIC_DID
              value: "did:web:{{ .Values.vsAgentName }}.{{ .Values.vsAgentDomain }}"
{{- with .Values.extraEnv }}
{{- toYaml . | nindent 12 }}
{{- end }}
            ports:
            -  containerPort: {{ .Values.adminPort }}
            -  containerPort: {{ .Values.agentPort }}
        {{- if .Values.database.enabled }}
         -  name: postgres
            image: postgres:15.2
            imagePullPolicy: Always
            env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.pwd }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            ports:
            -  containerPort: 5432
            volumeMounts:
            - name: {{ .Values.name }}-pg-pv-main
              mountPath: /var/lib/postgresql/data
        {{- end }}
        {{- if .Values.images.redis.enabled }}
         -  name: {{ .Values.name }}-redis-container
            image: "{{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}"
            imagePullPolicy: Always
            ports:
            -  containerPort: 6379
            volumeMounts:
            - name: {{ .Values.name }}-redis-main
              mountPath: /home/data
        {{- end }}
            volumeMounts:
            - name: {{ .Values.vsAgentName }}-vsa-pv
              mountPath: /root/.afj

         volumes:
         - name: {{ .Values.vsAgentName }}-vsa-pv
           persistentVolumeClaim:
             claimName: {{ .Values.vsAgentName }}-vsa-pv
        {{- if .Values.database.enabled }}
         - name: {{ .Values.name }}-pg-pv-main
           persistentVolumeClaim:
             claimName: {{ .Values.name }}-pg-pv-main
        {{- end }}
        {{- if .Values.images.redis.enabled }}
         - name: {{ .Values.name }}-redis-main
           persistentVolumeClaim:
             claimName: {{ .Values.name }}-redis-main
        {{- end }}
