name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-root:
    name: Validate Root
    runs-on: ubuntu-latest

    steps:
      - name: Checkout service-agent
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Check Format
        run: pnpm check-format

      - name: Check Types
        run: pnpm check-types

      - name: Test
        run: pnpm test

      - name: Validate Helm chart
        run: helm lint ./charts/vs-agent

      - name: Validate Helm chart Chatbot
        run: helm lint ./charts/chatbot

  validate-demo-dts:
    name: Validate Demo DTS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/demo-dts

    steps:
      - name: Checkout service-agent
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Check Format
        run: pnpm check-format

      - name: Check Types
        run: pnpm check-types
